# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '2.0.0a1.dev34+gddcd002f.d20230920'  # type: str
__version_tuple__ = version_tuple = (2, 0, 0, 'dev34', 'gddcd002f.d20230920')  # type: tuple[int | str, ...]
